<script setup>
    const wire = ref(null);
    const animateWire = () => {
        wire.value.classList.add("active");
    };

    //when the wire appears in the viewport, animate it
    onMounted(() => {
        const options = {
            root: null,
            rootMargin: "0px",
            threshold: 0.5,
        };
        const observer = new IntersectionObserver((entries) => {
            entries.forEach((entry) => {
                if (entry.isIntersecting) {
                    animateWire();
                }
            });
        }, options);
        observer.observe(wire.value);
    });
</script>

<template>
    <svg class="wire" ref="wire" width="100%" height="311" viewBox="0 0 1920 311" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
            d="M-37 21.1533C194.5 -80.3467 633.5 280.653 1096 197.653C1558.5 114.653 1877.5 154.653 2188 266.653"
            stroke="#E1E634"
            stroke-width="5"
            class="svg-elem-1"
        ></path>
        <path
            d="M-36 55.1535C195.5 -46.3465 633 292.653 1095.5 209.653C1558 126.653 1869.5 196.653 2180 308.653"
            stroke="#E1E634"
            stroke-width="5"
            class="svg-elem-2"
        ></path>
    </svg>
</template>

<style scoped>
/***************************************************
 * Generated by SVG Artista on 5/13/2024, 7:03:39 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/
svg .svg-elem-1 {
    stroke-dashoffset: 2274.3603515625px;
    stroke-dasharray: 2274.3603515625px;
    -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
    transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
}

svg.active .svg-elem-1 {
    stroke-dashoffset: 0;
}

svg .svg-elem-2 {
    stroke-dashoffset: 2263.753173828125px;
    stroke-dasharray: 2263.753173828125px;
    -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s;
    transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s;
}

svg.active .svg-elem-2 {
    stroke-dashoffset: 0;
}
</style>
